function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // death
	global.__objectDepths[1] = 0; // all_movables_objects
	global.__objectDepths[2] = 0; // all_land_objects_parent
	global.__objectDepths[3] = 0; // X_MAS_team
	global.__objectDepths[4] = 0; // Terror_Squad
	global.__objectDepths[5] = 0; // X_MAS_ally
	global.__objectDepths[6] = 0; // intro_object
	global.__objectDepths[7] = 1; // Hill_5
	global.__objectDepths[8] = 999999999; // terrain_1
	global.__objectDepths[9] = 0; // Puff_1
	global.__objectDepths[10] = 0; // Puff_2
	global.__objectDepths[11] = 0; // Explode
	global.__objectDepths[12] = 0; // Explode_2
	global.__objectDepths[13] = 0; // Blue_Ring
	global.__objectDepths[14] = 0; // effect_parent
	global.__objectDepths[15] = 0; // egg_pawn
	global.__objectDepths[16] = 0; // metal_sonic
	global.__objectDepths[17] = 0; // beetle
	global.__objectDepths[18] = 0; // ufo_tank
	global.__objectDepths[19] = 0; // hero_obj
	global.__objectDepths[20] = 0; // hero_info
	global.__objectDepths[21] = 0; // laser_ray
	global.__objectDepths[22] = 0; // bpla
	global.__objectDepths[23] = 0; // wave
	global.__objectDepths[24] = 0; // freeze
	global.__objectDepths[25] = 0; // landmine
	global.__objectDepths[26] = 0; // throw_grenade
	global.__objectDepths[27] = 0; // unit_hp
	global.__objectDepths[28] = 0; // ally_obj
	global.__objectDepths[29] = 0; // plasma_bomb
	global.__objectDepths[30] = -1; // bullet
	global.__objectDepths[31] = 0; // plasma
	global.__objectDepths[32] = 0; // grenade
	global.__objectDepths[33] = -3; // text_obj_white
	global.__objectDepths[34] = -3; // text_obj_red
	global.__objectDepths[35] = -3; // text_obj_red_12
	global.__objectDepths[36] = -2; // button_large_parent
	global.__objectDepths[37] = -2; // button_large_exit
	global.__objectDepths[38] = -2; // button_large_continue
	global.__objectDepths[39] = -2; // button_large_evac
	global.__objectDepths[40] = -2; // button_arrow
	global.__objectDepths[41] = -2; // button_arrow_red
	global.__objectDepths[42] = -1; // tabletop
	global.__objectDepths[43] = 0; // mouse_follower
	global.__objectDepths[44] = -1; // menu_small
	global.__objectDepths[45] = -1; // button_grenade
	global.__objectDepths[46] = -1; // button_medkit
	global.__objectDepths[47] = 0; // room_control
	global.__objectDepths[48] = 0; // block
	global.__objectDepths[49] = -3; // text_obj_red_28
	global.__objectDepths[50] = -3; // text_obj_red_28_left
	global.__objectDepths[51] = -3; // text_obj_white_28
	global.__objectDepths[52] = -3; // text_obj_white_28_c
	global.__objectDepths[53] = 10; // map_obj
	global.__objectDepths[54] = 2; // map_menu
	global.__objectDepths[55] = 9; // onmap_building
	global.__objectDepths[56] = 9; // onmap_city
	global.__objectDepths[57] = 9; // onmap_escort
	global.__objectDepths[58] = 9; // onmap_enemy
	global.__objectDepths[59] = 9; // onmap_enemysite
	global.__objectDepths[60] = 0; // map_objects
	global.__objectDepths[61] = 0; // time_m
	global.__objectDepths[62] = 0; // date
	global.__objectDepths[63] = -2; // button_large_base
	global.__objectDepths[64] = -2; // button_large_intercept
	global.__objectDepths[65] = -2; // button_large_plane
	global.__objectDepths[66] = -2; // button_large_research
	global.__objectDepths[67] = -2; // button_large_build
	global.__objectDepths[68] = -2; // button_large_ufopedia
	global.__objectDepths[69] = -2; // button_large_buy
	global.__objectDepths[70] = -2; // button_large_workshop
	global.__objectDepths[71] = -2; // button_large_sell
	global.__objectDepths[72] = -2; // button_large_info
	global.__objectDepths[73] = -2; // button_large_infantry
	global.__objectDepths[74] = -2; // button_large_q_yes
	global.__objectDepths[75] = -2; // button_large_q_no
	global.__objectDepths[76] = -2; // button_large_q_ok
	global.__objectDepths[77] = -2; // button_large_b_exit
	global.__objectDepths[78] = -2; // button_large_b_research
	global.__objectDepths[79] = -2; // button_large_b_construct
	global.__objectDepths[80] = -2; // button_large_b_buy
	global.__objectDepths[81] = -2; // button_large_b_weapon
	global.__objectDepths[82] = -1; // button_large_b_remove
	global.__objectDepths[83] = -2; // button_large_b_name
	global.__objectDepths[84] = -2; // button_large_b_infname
	global.__objectDepths[85] = -2; // button_large_b_planetth
	global.__objectDepths[86] = -2; // button_large_b_infdesc
	global.__objectDepths[87] = -2; // button_large_b_iweapon
	global.__objectDepths[88] = -1; // button_large_b_iremove
	global.__objectDepths[89] = -1; // button_large_b_designation
	global.__objectDepths[90] = -1; // button_large_b_idesignation
	global.__objectDepths[91] = -1; // button_large_b_premove
	global.__objectDepths[92] = -2; // button_large_memory
	global.__objectDepths[93] = -2; // button_large_intercapply
	global.__objectDepths[94] = -2; // button_large_build_onmap
	global.__objectDepths[95] = 1; // acc_button
	global.__objectDepths[96] = 0; // map_grid
	global.__objectDepths[97] = 3; // map_base
	global.__objectDepths[98] = 2; // draw_plane
	global.__objectDepths[99] = 2; // module_obj
	global.__objectDepths[100] = 2; // module_image
	global.__objectDepths[101] = 0; // ask_parent
	global.__objectDepths[102] = 0; // draw_onmap
	global.__objectDepths[103] = 1; // ask_build
	global.__objectDepths[104] = -1; // ask_build_onmap
	global.__objectDepths[105] = 1; // ask_techselect
	global.__objectDepths[106] = 1; // ask_plane
	global.__objectDepths[107] = 0; // ask_planeweapon
	global.__objectDepths[108] = 0; // ask_infweapon
	global.__objectDepths[109] = 0; // ask_infdesignation
	global.__objectDepths[110] = 1; // ask_constrselect
	global.__objectDepths[111] = 1; // ask_question
	global.__objectDepths[112] = 1; // ask_question_inter
	global.__objectDepths[113] = -1; // ask_question_m
	global.__objectDepths[114] = -1; // ask_question_p
	global.__objectDepths[115] = -1; // ask_question_i
	global.__objectDepths[116] = -1; // ask_question_plane_fight
	global.__objectDepths[117] = -1; // ask_question_plane_designation_reached
	global.__objectDepths[118] = 1; // ask_question_b
	global.__objectDepths[119] = -1; // ask_message
	global.__objectDepths[120] = 2; // background_map
	global.__objectDepths[121] = -2; // button_arrow_2
	global.__objectDepths[122] = -2; // button_arrow_2P
	global.__objectDepths[123] = -2; // button_arrow_2I
	global.__objectDepths[124] = -2; // button_arrow_2W
	global.__objectDepths[125] = 0; // background_line
	global.__objectDepths[126] = 0; // background_line2
	global.__objectDepths[127] = 0; // background_line3
	global.__objectDepths[128] = 0; // background_line4
	global.__objectDepths[129] = 0; // draw_bar
	global.__objectDepths[130] = 1; // ask_inf
	global.__objectDepths[131] = 0; // ask_escort
	global.__objectDepths[132] = -1; // select_inmenu
	global.__objectDepths[133] = 0; // mouse_target_inter
	global.__objectDepths[134] = 0; // draw_onmap_plane
	global.__objectDepths[135] = 0; // wikiimage_small
	global.__objectDepths[136] = 0; // wikiimage_medium
	global.__objectDepths[137] = 30; // plane_square_map
	global.__objectDepths[138] = 0; // music_commander
	global.__objectDepths[139] = 0; // plane_parent
	global.__objectDepths[140] = 0; // shell_parent
	global.__objectDepths[141] = -1; // XMAS_Plane
	global.__objectDepths[142] = 0; // EGG_Plane
	global.__objectDepths[143] = -1; // plane_commander
	global.__objectDepths[144] = 0; // plane_shell
	global.__objectDepths[145] = 0; // plane_shell_expl
	global.__objectDepths[146] = 0; // button_parent
	global.__objectDepths[147] = -1; // button_for_plane
	global.__objectDepths[148] = -1; // EGG_turret
	global.__objectDepths[149] = -1; // XMAS_turret


	global.__objectNames[0] = "death";
	global.__objectNames[1] = "all_movables_objects";
	global.__objectNames[2] = "all_land_objects_parent";
	global.__objectNames[3] = "X_MAS_team";
	global.__objectNames[4] = "Terror_Squad";
	global.__objectNames[5] = "X_MAS_ally";
	global.__objectNames[6] = "intro_object";
	global.__objectNames[7] = "Hill_5";
	global.__objectNames[8] = "terrain_1";
	global.__objectNames[9] = "Puff_1";
	global.__objectNames[10] = "Puff_2";
	global.__objectNames[11] = "Explode";
	global.__objectNames[12] = "Explode_2";
	global.__objectNames[13] = "Blue_Ring";
	global.__objectNames[14] = "effect_parent";
	global.__objectNames[15] = "egg_pawn";
	global.__objectNames[16] = "metal_sonic";
	global.__objectNames[17] = "beetle";
	global.__objectNames[18] = "ufo_tank";
	global.__objectNames[19] = "hero_obj";
	global.__objectNames[20] = "hero_info";
	global.__objectNames[21] = "laser_ray";
	global.__objectNames[22] = "bpla";
	global.__objectNames[23] = "wave";
	global.__objectNames[24] = "freeze";
	global.__objectNames[25] = "landmine";
	global.__objectNames[26] = "throw_grenade";
	global.__objectNames[27] = "unit_hp";
	global.__objectNames[28] = "ally_obj";
	global.__objectNames[29] = "plasma_bomb";
	global.__objectNames[30] = "bullet";
	global.__objectNames[31] = "plasma";
	global.__objectNames[32] = "grenade";
	global.__objectNames[33] = "text_obj_white";
	global.__objectNames[34] = "text_obj_red";
	global.__objectNames[35] = "text_obj_red_12";
	global.__objectNames[36] = "button_large_parent";
	global.__objectNames[37] = "button_large_exit";
	global.__objectNames[38] = "button_large_continue";
	global.__objectNames[39] = "button_large_evac";
	global.__objectNames[40] = "button_arrow";
	global.__objectNames[41] = "button_arrow_red";
	global.__objectNames[42] = "tabletop";
	global.__objectNames[43] = "mouse_follower";
	global.__objectNames[44] = "menu_small";
	global.__objectNames[45] = "button_grenade";
	global.__objectNames[46] = "button_medkit";
	global.__objectNames[47] = "room_control";
	global.__objectNames[48] = "block";
	global.__objectNames[49] = "text_obj_red_28";
	global.__objectNames[50] = "text_obj_red_28_left";
	global.__objectNames[51] = "text_obj_white_28";
	global.__objectNames[52] = "text_obj_white_28_c";
	global.__objectNames[53] = "map_obj";
	global.__objectNames[54] = "map_menu";
	global.__objectNames[55] = "onmap_building";
	global.__objectNames[56] = "onmap_city";
	global.__objectNames[57] = "onmap_escort";
	global.__objectNames[58] = "onmap_enemy";
	global.__objectNames[59] = "onmap_enemysite";
	global.__objectNames[60] = "map_objects";
	global.__objectNames[61] = "time_m";
	global.__objectNames[62] = "date";
	global.__objectNames[63] = "button_large_base";
	global.__objectNames[64] = "button_large_intercept";
	global.__objectNames[65] = "button_large_plane";
	global.__objectNames[66] = "button_large_research";
	global.__objectNames[67] = "button_large_build";
	global.__objectNames[68] = "button_large_ufopedia";
	global.__objectNames[69] = "button_large_buy";
	global.__objectNames[70] = "button_large_workshop";
	global.__objectNames[71] = "button_large_sell";
	global.__objectNames[72] = "button_large_info";
	global.__objectNames[73] = "button_large_infantry";
	global.__objectNames[74] = "button_large_q_yes";
	global.__objectNames[75] = "button_large_q_no";
	global.__objectNames[76] = "button_large_q_ok";
	global.__objectNames[77] = "button_large_b_exit";
	global.__objectNames[78] = "button_large_b_research";
	global.__objectNames[79] = "button_large_b_construct";
	global.__objectNames[80] = "button_large_b_buy";
	global.__objectNames[81] = "button_large_b_weapon";
	global.__objectNames[82] = "button_large_b_remove";
	global.__objectNames[83] = "button_large_b_name";
	global.__objectNames[84] = "button_large_b_infname";
	global.__objectNames[85] = "button_large_b_planetth";
	global.__objectNames[86] = "button_large_b_infdesc";
	global.__objectNames[87] = "button_large_b_iweapon";
	global.__objectNames[88] = "button_large_b_iremove";
	global.__objectNames[89] = "button_large_b_designation";
	global.__objectNames[90] = "button_large_b_idesignation";
	global.__objectNames[91] = "button_large_b_premove";
	global.__objectNames[92] = "button_large_memory";
	global.__objectNames[93] = "button_large_intercapply";
	global.__objectNames[94] = "button_large_build_onmap";
	global.__objectNames[95] = "acc_button";
	global.__objectNames[96] = "map_grid";
	global.__objectNames[97] = "map_base";
	global.__objectNames[98] = "draw_plane";
	global.__objectNames[99] = "module_obj";
	global.__objectNames[100] = "module_image";
	global.__objectNames[101] = "ask_parent";
	global.__objectNames[102] = "draw_onmap";
	global.__objectNames[103] = "ask_build";
	global.__objectNames[104] = "ask_build_onmap";
	global.__objectNames[105] = "ask_techselect";
	global.__objectNames[106] = "ask_plane";
	global.__objectNames[107] = "ask_planeweapon";
	global.__objectNames[108] = "ask_infweapon";
	global.__objectNames[109] = "ask_infdesignation";
	global.__objectNames[110] = "ask_constrselect";
	global.__objectNames[111] = "ask_question";
	global.__objectNames[112] = "ask_question_inter";
	global.__objectNames[113] = "ask_question_m";
	global.__objectNames[114] = "ask_question_p";
	global.__objectNames[115] = "ask_question_i";
	global.__objectNames[116] = "ask_question_plane_fight";
	global.__objectNames[117] = "ask_question_plane_designation_reached";
	global.__objectNames[118] = "ask_question_b";
	global.__objectNames[119] = "ask_message";
	global.__objectNames[120] = "background_map";
	global.__objectNames[121] = "button_arrow_2";
	global.__objectNames[122] = "button_arrow_2P";
	global.__objectNames[123] = "button_arrow_2I";
	global.__objectNames[124] = "button_arrow_2W";
	global.__objectNames[125] = "background_line";
	global.__objectNames[126] = "background_line2";
	global.__objectNames[127] = "background_line3";
	global.__objectNames[128] = "background_line4";
	global.__objectNames[129] = "draw_bar";
	global.__objectNames[130] = "ask_inf";
	global.__objectNames[131] = "ask_escort";
	global.__objectNames[132] = "select_inmenu";
	global.__objectNames[133] = "mouse_target_inter";
	global.__objectNames[134] = "draw_onmap_plane";
	global.__objectNames[135] = "wikiimage_small";
	global.__objectNames[136] = "wikiimage_medium";
	global.__objectNames[137] = "plane_square_map";
	global.__objectNames[138] = "music_commander";
	global.__objectNames[139] = "plane_parent";
	global.__objectNames[140] = "shell_parent";
	global.__objectNames[141] = "XMAS_Plane";
	global.__objectNames[142] = "EGG_Plane";
	global.__objectNames[143] = "plane_commander";
	global.__objectNames[144] = "plane_shell";
	global.__objectNames[145] = "plane_shell_expl";
	global.__objectNames[146] = "button_parent";
	global.__objectNames[147] = "button_for_plane";
	global.__objectNames[148] = "EGG_turret";
	global.__objectNames[149] = "XMAS_turret";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
